
development:
  adapter: postgresql
  encoding: unicode
  database: super3_development
  pool: 5
  host: localhost
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: super3_test
  pool: 5
  host: localhost
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: super3_production
  pool: 5
  username:
  password:
